services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
     - 3000:3000
  db:
    image: mysql:latest
    platform: linux/arm64/v8
    restart: always
    hostname: my-mysql
    environment:
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: mysql_user
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
    tty: true